Workout01
================
Dongneuk Kim
3/13/2019

    ## 
    ## Attaching package: 'dplyr'

    ## The following objects are masked from 'package:stats':
    ## 
    ##     filter, lag

    ## The following objects are masked from 'package:base':
    ## 
    ##     intersect, setdiff, setequal, union

2PT Effective Shooting % by Player
----------------------------------

| name           |  TotalShots|  ShotsMade|  PercentMade|
|:---------------|-----------:|----------:|------------:|
| Andre Iguodala |         210|        134|    0.6380952|
| Kevin Durant   |         643|        390|    0.6065319|
| Stephen Curry  |         563|        304|    0.5399645|
| Klay Thompson  |         640|        329|    0.5140625|
| Draymond Green |         346|        171|    0.4942197|

3PT Effective Shooting % by Player
----------------------------------

| name           |  TotalShots|  ShotsMade|  PercentMade|
|:---------------|-----------:|----------:|------------:|
| Klay Thompson  |         580|        246|    0.4241379|
| Stephen Curry  |         687|        280|    0.4075691|
| Kevin Durant   |         272|        105|    0.3860294|
| Andre Iguodala |         161|         58|    0.3602484|
| Draymond Green |         232|         74|    0.3189655|

Effective Shooting % by Player
------------------------------

| name           |  TotalShots|  ShotsMade|  PercentMade|
|:---------------|-----------:|----------:|------------:|
| Kevin Durant   |         915|        495|    0.5409836|
| Andre Iguodala |         371|        192|    0.5175202|
| Klay Thompson  |        1220|        575|    0.4713115|
| Stephen Curry  |        1250|        584|    0.4672000|
| Draymond Green |         578|        245|    0.4238754|

Shot chart of GSW(2016)
-----------------------

<img src="../images/gsw-shot-charts.png" width="80%" style="display: block; margin: auto;" />

Introduction
============

As everyone know, GSW is the best team in NBA. This workout is going to analyze how GSW be the best team in NBA league.

Motivation
==========

GSW is now one of the best team in NBA league. There are five popular star players in GSW, and eacth of them have their own role for team. Curious about their roles and scores distribution, so we are going to see score distribution of each player and analyze their character.

Analysis
========

As we can see in 2PT table, Kevin have the most two points totalshots and shotsmade, and Andre Iguodala have the lowest two points totalshots and shotsmade. From this data, we get to know that Kevin uses his height to get lots of totalshots and shotsmade. In contrast, Andre Iguodala have lowest shotsmade, but he has the highest percentage of goal successes. It means he usually attempts the shot when he has a good chance. Also, 3PT table shows GSW have the best 3 PTs shooters in the league. Curry gets 280 shotmade out of 687 totalshots, and Thompson gets 246 shotmades out of 580 totalshots. Even though both have lots of totalshots, they have a good percentage of 3 PTs shoot success(Curry has 40%, Thompson has 42%). Kevin Durant, who got into GSW this season, have 38% of shotsmade. Iguodala and Green get 58 and 74 shotsmade, which is about 35% of success rate. Third table shows effective shooting rate of each player.Durant gets 495 shotmades out of 915 totalshots, which is 54% of success. This means he is the key player of GSW. Curry tries 1250 shoots and make 575 successes, which is 46.7% of success. Another key player, Klay Thompson have 47% success rate. These players are the best players in NBA.
